### ISSUE TITLE
a few things :)

### ISSUE THREAD

**Issue by aligh95** [NilufarMohammadi1/NilaPackage#1]
First of all, thank you Niloufar for this good and compatible script. 😊😊

Here are a few things I thought, I could tell you about::  👀👀
1. Please add the ability to read from Excel and text files to this script.
2. Please add the feature of inserting mathematical operations on one or more columns.
3. Please separate the main script class from the initializer class.

**Comment by nilimohammadi** [comment]
Hi. Done! Thank you!!
